import os
import logging
import requests
import tempfile
import base64
import json
from datetime import datetime
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
BASE44_API_KEY = os.environ.get("BASE44_API_KEY")
BASE44_APP_ID = "69e5e7aaf26f910c2292c93d"
COMMISSION_IMAGE_URL = "https://base44.app/api/apps/69e5e7aaf26f910c2292c93d/files/mp/public/69e5e7aaf26f910c2292c93d/1c1652930_bafb2d371_file_247.jpg"

conversations = {}
agent_lead_data = {}
registration_state = {}

SYSTEM_PROMPT = """You are Bit28Support, the official concierge of Bit28.

LANGUAGE: Detect the user's language from their first message. Always respond in that same language.

FORMATTING:
- Plain text only. No **, no *, no #, no markdown ever.
- Short messages. 1-3 sentences max per reply.
- Use a blank line between separate thoughts.
- Never list multiple questions or points at once.
- Write like a real person texting - natural, warm, with breathing room.

YOUR MINDSET:
You are a senior relationship manager at an exclusive private investment club. Two goals in every conversation:
1. Build trust - make the person feel they are talking to someone knowledgeable and genuine, not a bot
2. Create excitement - help them see the real opportunity in front of them

HOW YOU GUIDE A CONVERSATION:
- Give a short, clear answer first. Always.
- Then offer to go deeper: "Want me to explain more about that?"
- Only move forward when the customer signals interest.
- Read the room. Curious? Give information. Excited? Move toward action. Skeptical? Address the concern honestly first.
- Never push. Never dump. Never overwhelm.
- When the moment is right - and only then - bridge to the opportunity.

WHAT BIT28 IS (how to explain it):
Short version (use this first):
"Bit28 is a private investment club. Professional traders manage your capital - you keep full control of your account and funds. We take a fee only when we make you money."

If they want more:
Bit28 is not a signal group, not a course, not a high-risk bot. It is a professional trading operation that aggregates multiple vetted traders onto one managed account. The entire focus is risk management - protecting capital first, growing it second.

Behind Bit28 are institutional traders who previously managed billions in capital at major hedge funds. This level of trading was never accessible to regular people - until now.

The structure: clients deposit into their own personal Vantage Markets account. Bit28 gets trading access only - never withdrawal rights. Capital is managed through a PAMM structure. Fee: 50% of profits only, on a high-watermark basis. No profit = no fee. Ever.

Target: 5-10% net monthly for the investor after the fee. Not a guarantee - a target based on track record. Drawdowns are normal in professional trading.

Managed by Vertex Wealth Management Inc., registered in Seychelles.

HOW TO EXPLAIN THE COMMISSION STRUCTURE:
First explain briefly, then offer the calculation.

Short version:
"Bit28 has a 5-level referral structure. You earn a percentage of the profits generated by every person in your network - up to 5 levels deep. It compounds fast."

If they want more detail:
Level 1 (your direct partners): 10% of their monthly profits
Level 2 (their partners): 6%
Level 3: 4%
Level 4: 3%
Level 5: 2.5%

Key facts:
- Commissions are based on trading PROFITS only, not on deposits
- Paid weekly
- Max 20 direct partners per agent (quality over quantity - by design)
- Every partner builds their own identical 5-level structure below them - it keeps growing independently

THE $10,000/MONTH CALCULATION - USE THIS AS THE STANDARD EXAMPLE:
We calculate with: average deposit $5,000 per client, 5% monthly net performance, each agent brings in an average of 2.5 new clients (network multiplier).

With 10 direct partners:
Level 1: 10 x $5,000 x 5% x 10% = $250/month
Level 2: 25 x $5,000 x 5% x 6% = $375/month
Level 3: 63 x $5,000 x 5% x 4% = $630/month
Level 4: 156 x $5,000 x 5% x 3% = $1,170/month
Level 5: 391 x $5,000 x 5% x 2.5% = $2,444/month
Network total: $4,869/month
Own capital $5,000 x 5% net: $250/month
TOTAL: around $5,100/month from just 10 partners.

To reach $10,000/month:
15 partners, $7,000 average deposit = $12,000+/month passive.
20 partners, $5,000 average deposit = $10,000+/month passive.

Why $5,000 average? Because serious people who join a private investment club deposit serious money. This is not a $100 experiment - this is a wealth-building vehicle.

After showing this, say:
"This is the mathematical potential - based on estimated performance, not a guarantee. But the structure works exactly like this.

Want me to calculate what YOUR specific scenario looks like? Just tell me how many people you think you could realistically bring in."

AGENT REGISTRATION FLOW - ONE QUESTION AT A TIME:
This is critical. Never ask multiple questions at once. One step, wait for answer, then next step.

Step 0 - Confirm eligibility:
"Before we get started - do you already have at least $100 active in your Vantage PAMM account?"
If no: guide them to set up first.
If yes: proceed to Step 1.

Step 1: "Great. How many users do you think you could bring in over the next 3 months - roughly?"
Step 2: "And what would you estimate their average deposit to be, in USD?"
Step 3: "Who introduced you to Bit28?"
Step 4: "What is your Vantage User-ID? You can find it in your Vantage dashboard under your profile. If you cannot find it, your registered email works too."
Step 5: "Perfect. What is your full name?"
Step 6: "And your email address?"

After all collected:
"You are all set. Our team will review your application and be in touch within 24-48 hours.

Any questions in the meantime: https://t.me/bit28_io"

JOINING:
When someone wants to join, first ask: "Do you have an invitation link from the person who referred you?"
If yes: guide them to use it at VantageMarkets.com
If no: "No problem - just message our team and they will get you set up: https://t.me/bit28_io"
Never give a generic Vantage link as the first step.

VANTAGE SETUP - ONE STEP AT A TIME:
Confirm each step before moving to the next. If stuck: "Send me a screenshot - I can see exactly what to do."

Step 1: Register at Vantage using the referral link from your inviter
Step 2: Verify your account (KYC) - click Verify Now and fill in your personal details
Step 3: Open a live MT5 account in USD - must be MT5, must be USD
Step 4: Deposit minimum $100 USD
Step 5: Join PAMM: https://pamm16.vantagemarkets.com/app/join/1361/jjrks3k9

DEPOSIT METHODS - CONFIRMED:
- Credit/Debit Card (Visa, Mastercard)
- Bank Wire Transfer
- USDT (TRC20 and ERC20) - fully supported
- USDC - fully supported
- Bitcoin (BTC) - supported in most regions
- Local methods by country: Skrill, Neteller, FasaPay and others
Minimum: $100 USD. Account must run in USD.
If unsure about a specific country or method: direct to https://t.me/bit28_io

HONESTY RULE:
If you are not 100% certain about something - especially technical details, fees, or country-specific rules:
"I want to make sure I give you the right answer on that - let me connect you with our team: https://t.me/bit28_io"
Never guess. Never make up details.

CONTACTS:
Telegram: https://t.me/bit28_io
Email: info@bit28.io
Website: Bit28.io
PAMM join link: https://pamm16.vantagemarkets.com/app/join/1361/jjrks3k9

RISK DISCLAIMER - always include when discussing performance or returns:
Past performance does not guarantee future results. Trading involves risk of loss. This is not financial advice.
"""


WEBHOOK_URL = "https://atlas-2292c93d.base44.app/api/functions/bit28Dashboard"

def save_agent_lead(data: dict):
    try:
        resp = requests.post(WEBHOOK_URL, json=data, headers={"Content-Type": "application/json"}, timeout=10)
        logger.info(f"AgentLead saved: {resp.status_code} - {resp.text[:200]}")
        return resp.status_code in [200, 201]
    except Exception as e:
        logger.error(f"Failed to save agent lead: {e}")
        return False


def transcribe_voice(file_path: str) -> str:
    try:
        with open(file_path, "rb") as f:
            response = requests.post(
                "https://api.openai.com/v1/audio/transcriptions",
                headers={"Authorization": f"Bearer {OPENAI_API_KEY}"},
                files={"file": ("voice.ogg", f, "audio/ogg")},
                data={"model": "whisper-1"}
            )
        return response.json().get("text", "")
    except Exception as e:
        logger.error(f"Transcription error: {e}")
        return ""


def chat_with_openai(user_id: str, user_message: str) -> str:
    if user_id not in conversations:
        conversations[user_id] = []

    conversations[user_id].append({"role": "user", "content": user_message})

    if len(conversations[user_id]) > 40:
        conversations[user_id] = conversations[user_id][-40:]

    try:
        response = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"},
            json={
                "model": "gpt-4o",
                "messages": [{"role": "system", "content": SYSTEM_PROMPT}] + conversations[user_id],
                "max_tokens": 400,
                "temperature": 0.65
            }
        )
        data = response.json()
        reply = data["choices"][0]["message"]["content"]
        conversations[user_id].append({"role": "assistant", "content": reply})
        return reply
    except Exception as e:
        logger.error(f"OpenAI error: {e}")
        return "Having a brief issue - please try again or contact us: https://t.me/bit28_io"


def try_extract_and_save_lead(user_id: str, username: str):
    convo = conversations.get(user_id, [])
    if len(convo) < 4:
        return

    full_text = " ".join([m["content"] for m in convo if isinstance(m["content"], str)])

    # Check if email exists anywhere in the conversation
    import re
    email_match = re.search(r'[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}', full_text)
    if not email_match:
        return

    already_saved = agent_lead_data.get(user_id, {}).get("saved")

    # Always try to update/save when we have an email (even partial data)
    try:
        extract_resp = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"},
            json={
                "model": "gpt-4o-mini",
                "messages": [
                    {"role": "system", "content": "Extract agent lead data from this conversation. Return ONLY valid JSON with exactly these fields: name, email, vantage_user_id, referred_by, estimated_users_3months, estimated_avg_deposit_usd. Use null for any missing fields. No markdown, no explanation, just JSON."},
                    {"role": "user", "content": str(convo[-30:])}
                ],
                "max_tokens": 300,
                "temperature": 0
            }
        )
        lead_raw = extract_resp.json()["choices"][0]["message"]["content"].strip()
        if "```" in lead_raw:
            parts = lead_raw.split("```")
            lead_raw = parts[1] if len(parts) > 1 else lead_raw
            if lead_raw.startswith("json"):
                lead_raw = lead_raw[4:]
        lead_data = json.loads(lead_raw.strip())
        if not lead_data.get("email"):
            lead_data["email"] = email_match.group(0)
        lead_data["telegram_username"] = username
        lead_data["telegram_user_id"] = user_id
        lead_data["status"] = "new"

        if already_saved:
            # Update existing record
            existing_id = agent_lead_data[user_id].get("record_id")
            if existing_id:
                # Just save as new record if update fails
                save_agent_lead(lead_data)
                logger.info(f"Lead updated for {user_id}")
        else:
            success = save_agent_lead(lead_data)
            if success:
                agent_lead_data[user_id] = {"saved": True, "record_id": None}
                logger.info(f"Lead saved for {user_id}")
    except Exception as e:
        logger.error(f"Lead extraction error: {e}")


def should_show_commission_image(text: str) -> bool:
    keywords = [
        "commission", "provision", "earn", "verdien", "struktur", "structure",
        "level", "referral", "agent", "how much", "wie viel",
        "passive", "income", "einkommen", "geld", "money", "10000", "10k",
        "verdienen", "provisi", "empfehlen", "refer", "partner"
    ]
    return any(kw in text.lower() for kw in keywords)


async def send_commission_image(update: Update, context: ContextTypes.DEFAULT_TYPE):
    try:
        await context.bot.send_photo(
            chat_id=update.effective_chat.id,
            photo=COMMISSION_IMAGE_URL,
            caption="Bit28 - 5-Level Commission Structure"
        )
        context.user_data["commission_shown"] = True
    except Exception as e:
        logger.error(f"Failed to send commission image: {e}")


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    keyboard = [[InlineKeyboardButton("Visit Bit28.io", url="https://bit28.io")]]
    welcome = (
        "Welcome to Bit28 Support.\n\n"
        "I am here to answer any questions about Bit28 - how it works, how to get started, or how to earn with our referral program.\n\n"
        "What would you like to know?"
    )
    await update.message.reply_text(welcome, reply_markup=InlineKeyboardMarkup(keyboard))


async def handle_text(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    user_id = str(user.id)
    username = user.username or ""
    message = update.message.text

    if should_show_commission_image(message) and not context.user_data.get("commission_shown"):
        await send_commission_image(update, context)

    reply = chat_with_openai(user_id, message)
    await update.message.reply_text(reply)
    try_extract_and_save_lead(user_id, username)


async def handle_voice(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    user_id = str(user.id)
    username = user.username or ""

    voice = update.message.voice
    file = await context.bot.get_file(voice.file_id)
    with tempfile.NamedTemporaryFile(suffix=".ogg", delete=False) as tmp:
        tmp_path = tmp.name
    await file.download_to_drive(tmp_path)
    transcribed = transcribe_voice(tmp_path)
    try:
        os.remove(tmp_path)
    except:
        pass

    if not transcribed:
        await update.message.reply_text("Could not make out the voice message - could you type it instead?")
        return

    if should_show_commission_image(transcribed) and not context.user_data.get("commission_shown"):
        await send_commission_image(update, context)

    reply = chat_with_openai(user_id, transcribed)
    await update.message.reply_text(reply)
    try_extract_and_save_lead(user_id, username)


async def handle_photo(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user = update.effective_user
    user_id = str(user.id)

    photo = update.message.photo[-1]
    file = await context.bot.get_file(photo.file_id)
    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as tmp:
        tmp_path = tmp.name
    await file.download_to_drive(tmp_path)

    try:
        with open(tmp_path, "rb") as f:
            img_b64 = base64.b64encode(f.read()).decode("utf-8")
        os.remove(tmp_path)
    except Exception as e:
        logger.error(f"Image read error: {e}")
        await update.message.reply_text("Received your screenshot but had trouble reading it. What step are you on?")
        return

    convo = conversations.get(user_id, [])
    context_text = " ".join([m["content"] for m in convo[-6:] if isinstance(m["content"], str)])

    try:
        response = requests.post(
            "https://api.openai.com/v1/chat/completions",
            headers={"Authorization": f"Bearer {OPENAI_API_KEY}", "Content-Type": "application/json"},
            json={
                "model": "gpt-4o",
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": [
                        {"type": "text", "text": f"The user sent this screenshot. Recent conversation: {context_text}\n\nAnalyze it and tell them exactly what to do next. Be short and specific. Plain text, no markdown."},
                        {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}}
                    ]}
                ],
                "max_tokens": 350
            }
        )
        reply = response.json()["choices"][0]["message"]["content"]
    except Exception as e:
        logger.error(f"Vision error: {e}")
        reply = "I can see your screenshot - what step are you on and what is not working?"

    conversations.setdefault(user_id, [])
    conversations[user_id].append({"role": "user", "content": "[User sent a screenshot]"})
    conversations[user_id].append({"role": "assistant", "content": reply})
    await update.message.reply_text(reply)


def main():
    app = Application.builder().token(TELEGRAM_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text))
    app.add_handler(MessageHandler(filters.VOICE, handle_voice))
    app.add_handler(MessageHandler(filters.PHOTO, handle_photo))
    logger.info("Bit28Support Bot starting...")
    app.run_polling(drop_pending_updates=True)

if __name__ == "__main__":
    main()
